### ISSUE TITLE
Wrong bullet point format from html string

### ISSUE THREAD

**Issue by neobeppe** [instacart/Nantes#56]
**Describe the bug**
When using bullet points from html string transformed in attributed string only the first line is well formatted. After fist line break text is not aligned with first word

**Smartphone (please complete the following information):**
 - iPhone

**Comment by neobeppe** [comment]
![IMG_3213](https://user-images.githubusercontent.com/7167022/80212890-9e478800-8638-11ea-91be-ad8b55af1552.png)

**Comment by andreaslindahl** [comment]
I also stumbled on a similar bug. It seems attributes set on the attributed string aren't used. When setting the attributedText property of the label, NantesLabel sets the text property of the label to attributedText.string, instead of setting the labels attributedText property to your attributed string.
